### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by taninwat019** [taninwat019/Project_Final#1]

**Comment by taninwat019** [comment]
3ce8a51d1854ea886b7d072d0c076f726441c1db

**Comment by taninwat019** [comment]
70662acf7e34540f320673a5e62f0ba4d1dcda7a : Create cart

**Comment by taninwat019** [comment]
e2ce0bde06a48a6c28339cbe0bba60b992e47cd7 : Add function scroll top

**Comment by taninwat019** [comment]
331060e9c2727298e7cd0e886d52d34de4022d3e : Add list menu

**Comment by taninwat019** [comment]
bd95b7635f060ede1719a4e57fd8c883e49abbf3 : Edit Cart

**Comment by taninwat019** [comment]
1c1d57dfd3f407f17669e90789fb6cca8d2020fa : Edit cart and menu (HTML, CSS)

**Comment by taninwat019** [comment]
1466683f0c865c8ab85ecd96e35b28c6568b049c : Update to EJS

**Comment by taninwat019** [comment]
d68bc97137daf8b3bb7df5d7125722d59875bafc : Edit decoration

**Comment by thiwakonsakunchao** [comment]
6949584f32e5c3504f6174e891bf4b8a52d50403 : Change image promo
