### ISSUE TITLE
Tracking Page

### ISSUE THREAD

**Issue by thiwakonsakunchao** [taninwat019/Project_Final#10]

**Comment by thiwakonsakunchao** [comment]
af00bab3e7ce0386b825985cc1d6c89e17a106c4 : Create tracking.html

**Comment by thiwakonsakunchao** [comment]
a5d92b9212e2eed42f658317d4e2c3a0b33d225f : Add detail tracking and css

**Comment by taninwat019** [comment]
1466683f0c865c8ab85ecd96e35b28c6568b049c :Update to EJS
