### ISSUE TITLE
Admin Page

### ISSUE THREAD

**Issue by taninwat019** [taninwat019/Project_Final#11]

**Comment by taninwat019** [comment]
8e0d7143d8414ff1fa08d013880f1437965057f4 : Add detail

**Comment by taninwat019** [comment]
1466683f0c865c8ab85ecd96e35b28c6568b049c :Update to EJS

**Comment by taninwat019** [comment]
d68bc97137daf8b3bb7df5d7125722d59875bafc : Edit decoration

**Comment by thiwakonsakunchao** [comment]
393d0881b9e74fdaff91cc263188843e37a18e87 : Change status button

**Comment by thiwakonsakunchao** [comment]
1b54f3125bc665b268b25a1668c5ffbd52d5ef20 : Update admin page when user checkout
