### ISSUE TITLE
Function Main Page

### ISSUE THREAD

**Issue by taninwat019** [taninwat019/Project_Final#14]
e2ce0bde06a48a6c28339cbe0bba60b992e47cd7 : Add function scroll top

**Comment by taninwat019** [comment]
25e75951058e7bcce30b35149c7cef324cdef1e0 : Add function category

**Comment by taninwat019** [comment]
9af89792dc7da9777ca9e86bd2da90a8b0b9c6dc : Remove item

**Comment by taninwat019** [comment]
1877ef3cac18f1486bb6c1926585f50851059c7f : Calculate price, Add item, Change quantity

**Comment by taninwat019** [comment]
2944a7e0ab9b9021d1fa52020e03e78e3f7abc6b: Edit code in main.js

**Comment by taninwat019** [comment]
52f7c76e3eb7eaa9d40e85488c705c55235c87c8 : Menu can compair with collection (MongoDB)

**Comment by thiwakonsakunchao** [comment]
045659a53efa597e8dadadfc78276cb03a6d643f : Update cart system

**Comment by thiwakonsakunchao** [comment]
58d93a49558f2066abe5ad032a19c56ca1e90b40 : In cart have show image price and quantity
