### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by thiwakonsakunchao** [taninwat019/Project_Final#2]

**Comment by thiwakonsakunchao** [comment]
640d7dcfef69284c880bc14c499ba364286fd6ed

**Comment by thiwakonsakunchao** [comment]
3be1f5be8a0cb2e99efae0653ad0e189ca9dcd70 : Add detail and login css

**Comment by thiwakonsakunchao** [comment]
640d7dcfef69284c880bc14c499ba364286fd6ed : Add guest button

**Comment by taninwat019** [comment]
4ddfdc32d846f7b4f0ddd07cfc67c679a67b9525 :Update to EJS
