### ISSUE TITLE
Register Page

### ISSUE THREAD

**Issue by thiwakonsakunchao** [taninwat019/Project_Final#7]

**Comment by thiwakonsakunchao** [comment]
cb780a1bf8f618c55af66d1da10118f0cb089827

**Comment by thiwakonsakunchao** [comment]
cb780a1bf8f618c55af66d1da10118f0cb089827 : Add detail register and css

**Comment by taninwat019** [comment]
4ddfdc32d846f7b4f0ddd07cfc67c679a67b9525 :Update to EJS
